### ISSUE TITLE
[Task](core):  aurora deployment

### ISSUE THREAD

**Issue by andypf** [cobaltcore-dev/aurora-dashboard#24]
**Task Description**
Aurora should be deployable and running against common openstack devstack and converged cloud backend. 

**Sub-tasks**

- [ ] Create aurora images, polaris and portal images
- [ ] Create a virtual machine to run devstack and make it accessable 
- [ ] Create a pipeline to deploy aurora. One pod against converged cloud (aurora-cc) and one against devstack (aurora-devstack)
- [ ] Add e2e tests
